### ISSUE TITLE
Support required for Microservices.

### ISSUE THREAD

**Issue by karthik-minnikanti** [Pythagora-io/pythagora#27]
When attempting to run multiple microservices on the same machine, the following error message is displayed:

**Error: listen EADDRINUSE: address already in use.** 

**Steps to Reproduce:**
Run multiple microservices on the same machine, each listening on a different port.
Observe that the error message "Port is already in use" is displayed for some of the microservices, preventing them from starting.

**Expected Behavior:**
Each microservice should start successfully and listen on the specified port without any errors.

**Actual Behavior:**
The error message "Port is already in use" is displayed for all of the microservices, preventing them from starting.

**Suggested Solution:**
change node options from --inspect to  --inspect=0 in run.bash file.

**Comment by LeonOstrez** [comment]
Hey @karthik-minnikanti , thank you so much for trying out Pythagora and reaching out!

It could be that issue occurs because of our Redis interceptor. Are you using Redis in your project? If you are not using Redis, can you please try running Pythagora command but at the end of it just add "--ignore-redis" flag.

Also can you please give me more information on error message "Error: listen EADDRINUSE: address already in use.". Does it say maybe which port is already used?

**Comment by karthik-minnikanti** [comment]
Hi @LeonOstrez , we are not using redis.  

this is the exact error. 

Starting inspector on 127.0.0.1:9229 failed: address already in use

**Comment by LeonOstrez** [comment]
@karthik-minnikanti  thank you so much!

Your suggestions are [merged](https://github.com/Pythagora-io/pythagora/pull/32) and publish with Pythagora version 0.0.52.

Please let me know how Pythagora is working for you after these updates.
