### ISSUE TITLE
Errors are not being shown in terminal or error log

### ISSUE THREAD

**Issue by jmschrack** [Pythagora-io/pythagora#43]
When running into errors, the terminal just shows "[object Object]pythagora_end:"
If I check the error logs, it just contains a JSON array of all the functions it tried, but doesn't show the error message.

I'm running the pythagora api server locally, and if I add a console.log to print out the stringified response in `resFromOpenAI.on('data',...` i can see the actual error object. (In this case, I'm rate limited)

![image](https://github.com/Pythagora-io/pythagora/assets/5498853/80d91b53-88e8-44e4-8277-1c1f44460cd8)

**Comment by LeonOstrez** [comment]
Hey @jmschrack can you please check what version of Pythagora you are using. We released new version today which also had updates on our backend server so that could be the reason. You should be using pythagora@0.0.68.

If you are using that version of Pythagora and still have error, can you please tell me what is your node version. Also, did you setup openai_api_key or pythagora_api_key?

**Comment by jmschrack** [comment]
@LeonOstrez I'm currently using 0.0.68  and the server is the master branch from 9:30amEST today.
I'm using a openai_api_key

**Comment by LeonOstrez** [comment]
You are correct! Thanks for reporting this. I just did a fix and published version 0.0.69. Please try that version of pythagora and let me know if it works. 

Also, if you are getting error using openai_api_key and you see message "Error: The model: `gpt-4` does not exist. Code: model_not_found" that means that your openai api key has no access to gpt4 and we are using only gpt4.

If you don't have access to gpt4 and still want to try pythagora you can send me email to leon@pythagora.ai and i will create pythagora_api_key for you so you can try it out.

**Comment by jmschrack** [comment]
@LeonOstrez now it doesn't show any error message, and just ends with `No tests generated!
Bash script exited with code 0`

I am lacking gpt-4 access, but I don't see any error.

FWIW I figured out a way to make the pythagora API server use gpt-3.5-turbo instead of gpt-4  and it works pretty good.  https://github.com/Pythagora-io/api/issues/4   

(To test the 0.0.69 version, I set the server back to gpt-4 to try and get a model_not_found error)

**Comment by LeonOstrez** [comment]
Can you please share full screenshot of your terminal/cmd ? There should be some other logs showing you where you can see errors... 

We don't support gpt3.5 because our prompts are made and tested for gpt4, which has shown to have much better performance. Quality of tests with gpt3.5 is not good enough.
