### ISSUE TITLE
How do you capture network traffic?

### ISSUE THREAD

**Issue by joshidp** [Pythagora-io/pythagora#52]
How do you capture network traffic?

Is there any change required in actual service code? If not, then how externally traffic can be monitored?

Thanks!

**Comment by LeonOstrez** [comment]
hey @joshidp I'm so sorry, I don't know how i missed your issue.

If you are asking about [integration testing](https://github.com/Pythagora-io/pythagora/blob/main/src/docs/integration/README.md) then answer is that we are using module patching. It is a way to modify existing modules with your own functionality. For example, we do it to ["express"](https://www.npmjs.com/package/express) module so that we can set our own middlewares and functions that are called once express server is being started. We are currently patching http, express, jwt and mongodb. That is why this is stack that we support and to support more we have to implement it. Once we have all patches in place we start server and can intercept requests and store all needed data.

If you are asking about [unit testing](https://github.com/Pythagora-io/pythagora) in that case answer is we don't capture network traffic. Unit tests are generated on static code without any network traffic (for now, we will see if we will change that in future).

I hope that answers your question. Let me know if something else is not clear.
