### ISSUE TITLE
To say this is free is misleading

### ISSUE THREAD

**Issue by Kelvinm** [Pythagora-io/pythagora#73]
you have a subscription based service.  

This is not the same as being free.  

I don't mind that there is a subscription fee, but it seems **VERY misleading** to say that it is free.

**Comment by LeonOstrez** [comment]
Hi @Kelvinm ,

I am assuming you opened the issue in the wrong repository. This is our previous project which has not been maintained since summer 2023.

You are probably referring to [GPT Pilot](https://github.com/Pythagora-io/gpt-pilot) which is the core technology for Pythagora VS Code extension. In that case, I suggest checking [our guide on how to use Pythagora VS Code extension for free using Local LLMs](https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs). We are charging $0 for extension and this is a 100% free way to use extension.

If you have any more concerns please feel free to reach out.
All the best
Leon
